# This is the main config file for the budget

vars:
  # Number of teams in current year
  teams: 24

  # Number of students in current year
  students: 6 * teams

  # Number of dev kits we'll own in the current year
  dev_kits: 8

  # Total number of kits we'll own in the current year
  total_kits: teams * 1.25 + dev_kits

  #########################################################
  # The following variables all refer to the next SR year,
  # kit will need to be manufactured in the current year.

  # Number of teams next year
  next_year_teams: 1.5 * teams

  # Number of dev kits we'll own next year
  next_year_dev_kits: dev_kits + 5

  # Total number of kits we'll own next year
  next_year_total_kits: next_year_teams * 1.25 + next_year_dev_kits

  # Number of kits to manufacture in the current year
  new_kits: next_year_total_kits - total_kits
