summary: Production company logistics

cost: 1380.00

description: >-
  Transport and misc consumables from production company (Bennellick
  Engineering Ltd.).  Based on their invoice.

# Whether the item/service can only be used once
consumable: true

closed: true
